### ISSUE TITLE
Only translate diff changes

### ISSUE THREAD

**Issue by eonist** [eonist/Babel#5]
Add this later

**Comment by eonist** [comment]
get commit hash of prev commit

Summary:
This GitHub Action workflow demonstrates how to get the git commit hash of the previous commit. Here's what it does:

It uses the actions/checkout@v2 action to check out the repository code.
In a subsequent step, it fetches the latest changes from the remote repository.
It then uses Git commands to get the hash of the previous commit (HEAD^).
The commit hash is stored in an environment variable called COMMIT_HASH.
Finally, it uses this variable in a subsequent step to demonstrate how to use it.
Best practices followed include:

Using official GitHub Actions for checking out code.
Fetching latest changes before calculating the previous commit hash.
Using environment variables to store and pass data between steps.
This approach allows you to access the hash of the previous commit in your workflow, which can be useful for tagging builds, setting cache keys, or other purposes that require knowing the previous commit's information [1](https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action)[2](https://github.com/orgs/community/discussions/25989).
```
name: CI Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Get previous commit hash
        id: prev_commit
        run: |
          git fetch origin master
          COMMIT_HASH=$(git rev-parse HEAD^)
          echo "Previous commit hash: $COMMIT_HASH" >> $GITHUB_ENV
        
      - name: Use previous commit hash
        run: |
          echo "Using previous commit hash: ${{ env.COMMIT_HASH }}"

```

or 


```
name: Get Previous Commit Hash

on:
  push:
    branches:
      - main

jobs:
  get-previous-commit-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get previous commit hash
        run: echo "Previous commit hash: $(git rev-parse HEAD^1)"

```

store output:
```
  - name: Get previous commit hash
    id: get_prev_commit
    run: echo "::set-output name=commit_hash::$(git rev-parse HEAD^1)"

  - name: Use previous commit hash
    run: echo "The previous commit hash is ${{ steps.get_prev_commit.outputs.commit_hash }}"


```

**Comment by eonist** [comment]
in github action: how can I read the content of a file named text.txt in the previous commit

Summary:
This GitHub Action workflow demonstrates how to read the content of a file named text.txt from the previous commit. Here's what it does:

It uses the actions/checkout@v2 action to check out the repository code.
In a subsequent step, it checks out the previous commit using HEAD^.
It reads the content of text.txt using the cat command.
The file content is stored in an environment variable called CONTENT.
After reading the file, it switches back to the master branch.
Finally, it uses this variable in a subsequent step to demonstrate how to use it.
Best practices followed include:

Using official GitHub Actions for checking out code.
Cleaning up the working directory after reading the file.
Using environment variables to store and pass data between steps.
This approach allows you to access the content of a specific file from the previous commit in your workflow, which can be useful for various purposes such as comparing changes, generating release notes, or other tasks that require knowledge of the previous state of the repository [1](https://stackoverflow.com/questions/71838806/get-last-commit-of-file-in-github-actions-pr)[3](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files).


```
name: Read Previous Commit File Content
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Read text.txt from previous commit
        id: prev_commit
        run: |
          git checkout HEAD^
          COMMIT_HASH=$(git rev-parse HEAD)
          CONTENT=$(cat text.txt)
          echo "Content of text.txt from previous commit: $CONTENT" >> $GITHUB_ENV
          git checkout master
          
      - name: Use file content
        run: |
          echo "File content: ${{ env.CONTENT }}"

```


or

To read the content of a file named text.txt from the previous commit in a GitHub Action workflow, you can follow these steps:

```
name: Read File from Previous Commit

on:
  push:
    branches:
      - main

jobs:
  read-previous-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Read text.txt from previous commit
        id: read_file
        run: |
          PREV_COMMIT_HASH=$(git rev-parse HEAD^1)
          git show $PREV_COMMIT_HASH:text.txt

```

Using the file content:
If you need to capture the content of the file for use in later steps, you can modify the run block to save the content to a file or output it as an environment variable:

```
      - name: Save text.txt content from previous commit
        id: read_file
        run: |
          PREV_COMMIT_HASH=$(git rev-parse HEAD^1)
          CONTENT=$(git show $PREV_COMMIT_HASH:text.txt)
          echo "$CONTENT" > previous_text.txt
          echo "::set-output name=file_content::$CONTENT"
          
      - name: Display file content
        run: echo "The content of text.txt from the previous commit is: ${{ steps.read_file.outputs.file_content }}"

```
